export const authTypes = {
    AUTH_START: 'AUTH_STARTING',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAIL: 'AUTH_FAIL',

    REGISTER_START: 'REGISTER_START',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',

    VENDOR_REG_START: 'VENDOR_REG_START',
    VENDOR_REG_SUCCESS: 'VENDOR_REG_SUCCESS',
    VENDOR_REG_FAIL: 'VENDOR_REG_FAIL',


    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    
    PROFILE_START: 'PROFILE_START',
    PROFILE_SUCCESS: 'PROFILE_SUCCESS',
    PROFILE_FAIL: 'PROFILE_FAIL',
};

export const vendorTypes = {
    FETCH_VENDOR_START: 'FETCH_VENDOR_START',
    FETCH_VENDOR_SUCCESS: 'FETCH_VENDOR_SUCCESS',
    FETCH_VENDOR_FAIL: 'FETCH_VENDOR_FAIL',
}